image: registry.secoder.net/tool/deployer

stages:
    - test
    - build
    - deploy

unit-test:
  image: python:3.8.5
  stage: test
  variables:
    MYSQL_ROOT_PASSWORD: "password_for_test"
  services:
    - name: registry.secoder.net/antijuan/backend:db
      alias: db-test
  before_script:
    - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements_dev.txt
  script:
    - coverage run --source book/views -m pytest --junit-xml=xunit-reports/xunit-result.xml
    - ret=$?
    - coverage xml -o coverage-reports/coverage.xml
    - coverage report
    - exit $ret
  after_script:
    - SUFFIX=$RANDOM
    - curl "http://10.0.0.11/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

style_test:
    image: python:3.8.5
    stage: test
    before_script:
        - pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements_dev.txt
    script:
        - pylint book/views
        - PYLINT_RET=$?
        - exit $PYLINT_RET

build:
  stage: build
  script:
    - export BUILD_IMAGE_NAME=$CI_REGISTRY_IMAGE
    - export BUILD_IMAGE_TAG=$CI_COMMIT_REF_SLUG
    - export BUILD_IMAGE_USERNAME=$CI_REGISTRY_USER
    - export BUILD_IMAGE_PASSWORD=$CI_REGISTRY_PASSWORD
    - deployer build
  only:
    - master
    - dev

deploy:
  stage: deploy
  script:
    - deployer dyno replace $CI_PROJECT_NAME "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" "$REGISTRY_USER" "$REGISTRY_PWD"
  only:
    - master
    - dev

