# Generated by Django 3.1.7 on 2021-04-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('size', models.CharField(choices=[('L', '大型'), ('M', '中型'), ('S', '小型')], max_length=1)),
                ('capacity', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('teacher_only', models.BooleanField(default=False)),
                ('cs_only', models.BooleanField(default=False)),
                ('has_screen', models.BooleanField(default=False)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_mic', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
                ('terminal_token', models.CharField(max_length=32, unique=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.building')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='book.institute')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=16, unique=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('fullname', models.CharField(max_length=32)),
                ('is_teacher', models.BooleanField(default=False)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('role', models.CharField(choices=[('U', '普通用户'), ('A', '管理员'), ('R', '超级管理员')], max_length=1)),
                ('token', models.CharField(max_length=32, unique=True)),
                ('token_expire_time', models.DateTimeField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.department')),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.institute')),
            ],
        ),
        migrations.CreateModel(
            name='RoomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('admins', models.ManyToManyField(to='book.User')),
                ('rooms', models.ManyToManyField(to='book.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_span', models.BigIntegerField()),
                ('apply_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('approval_result', models.BooleanField(blank=True, null=True)),
                ('refuse_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('approval_time', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=16, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('leave_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('W', '等待审批'), ('A', '审批通过'), ('R', '已被拒绝'), ('C', '已撤销'), ('E', '已过期'), ('U', '正在使用'), ('F', '已完成'), ('L', '已完成（晚退）'), ('B', '签到超时')], max_length=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_reservations', to='book.user')),
                ('approval_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_reservations', to='book.user')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='book.room')),
            ],
        ),
    ]
