# Generated by Django 3.1.7 on 2021-05-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unban_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
