# Generated by Django 3.1.7 on 2021-05-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user_unban_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unban_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
